[project]
name = "lost_in_the_metaverse_purplehippo911"
version = "0.0.1"
authors = [
  { name="Purplehippo911", email="oceanrabbit0101@protonmail.com" },
]
description = "A small RPG game run in the terminal"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/purplehippo911/lost_in_the_metaverse"
"Bug Tracker" = "https://github.com/purplehippo911/lost_in_the_metaverse/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"